# Generated by Django 5.2.4 on 2026-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_about_alter_user_name_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="github_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на профиль GitHub",
            ),
        ),
    ]
