# Generated by Django 5.2.4 on 2026-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="Название проекта",
                max_length=200,
                verbose_name="Название проекта",
            ),
        ),
    ]
