# Generated by Django 5.2.4 on 2026-04-24 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_participants_alter_project_skills_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "проект", "verbose_name_plural": "Проекты"},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "навык", "verbose_name_plural": "Навыки"},
        ),
    ]
