# Пользователь
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
USER_GITHUB_URL_MAX_LENGTH = 500

# Проект
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_GITHUB_URL_MAX_LENGTH = 500
PROJECT_STATUS_MAX_LENGTH = 6

# Навыки
SKILL_NAME_MAX_LENGTH = 124
AUTOCOMPLETE_LIMIT = 10

PAGINATE_BY = 12

OPEN_STATUS = 'open'
CLOSED_STATUS = 'closed'

STATUS_CHOICES = (
    (OPEN_STATUS, 'Открыт'),
    (CLOSED_STATUS, 'Закрыт'),
)
